

try:
    5/0


except Exception as ret :
    print("%s wrong has happend"%ret)

else :
    print("No wrong happened")
finally :
    print("programme run sucess....")


